const Map<String, String> examMacros = {
  'PIEL': 'PIEL Y FANERAS: SIN ALTERACIÓN, SIN SANGRADO EVIDENTE.',
  'CABEZA':
      'CABEZA: NORMOCEFALO, SIMETRICO, SIN MALFORMACIONES CRANEOFACIALES VISIBLES.',
  'OJOS': 'OJOS: VISION NORMAL, PUPILAS ISOCORICAS, REACTIVAS A LA LUZ.',
  'NARIZ': 'NARIZ: PERMEABLE, SIN SECRECIONES PATOLÓGICAS.',
  'BOCA': 'BOCA: MUCOSAS HÚMEDAS, NO LESIONES ORALES.',
  'OIDOS': 'OÍDOS: CONDUCTO AURICULAR SIN OBSTRUCCIÓN, AUDICIÓN PRESERVADA.',
  'OROFARINGE': 'OROFARINGE: AMIGDALAS SIN ENROJECIMIENTO EXCESIVO.',
  'CUELLO': 'CUELLO: SIN ADENOPATÍAS PALPABLES, SIN RIGIDEZ.',
  'TÓRAX': 'TÓRAX: SIMÉTRICO, MOVIMIENTOS RESPIRATORIOS CONSERVADOS.',
  'CAMPOS_PULMONARES':
      'CAMPOS PULMONARES: MURMULLO VESICULAR CONSERVADO, SIN ESTERTOS.',
  'RUIDOS_CARDIACOS': 'RUIDOS CARDIACOS: RITMO REGULAR, SIN SOPLOS CLAROS.',
  'ABDOMEN':
      'ABDOMEN: BLANDO, NO DISTENDIDO, DOLORES LOCALIZADOS SI LOS HUBIERA.',
  'EXTREMIDADES': 'EXTREMIDADES: SIN EDEMAS, PERFUSIÓN ADECUADA.',
  'NEURO': 'SISTEMA NEUROLÓGICO: MARCHA ESTABLE, REFLEJOS PRESENTES, ORIENTADO.'
};

const Map<String, String> labMacros = {
  'GASO': 'GASOMETRÍA ARTERIAL:\nPH: \nPCO2:  mmHg\nPO2:  mmHg\nHCO3:  mEq/L'
};

const Map<String, String> indiMacros = {
  'K_REP': 'REPOSICIÓN DE POTASIO:\n- CLORURO DE SODIO 0.9% 250ML MÁS CLORURO DE POTASIO 20ML MÁS SULFATO DE MAGNESIO 10ML VÍA INTRAVENOSA. PASAR EN 1 HORA.',
  'DOLOR': 'TERAPIA DEL DOLOR:\n- CLORURO DE SODIO AL 0.9% 300 ML MÁS TRAMADOL 300 MG MÁS METOCLOPRAMIDA 20 MG. PASAR A 20 ML/HORA.\n- KETOROLACO 60 MG PRN',
  'ANTICONV': 'TERAPIA ANTICONVULSIVANTE:\n- DIAZEPAM 10MG + SOLUCIÓN SALINA 0.9% 10CC, IV 2MG/MIN Y CONTINUAR A DOSIS RESPUESTA (DOSIS MÁXIMA 20MG)\n- FENITOINA 1GR (4 AMPOLLAS DE 250 MG) + SOLUCIÓN SALINA 0.9% 250CC, IV EN 20 MIN',
  'HIDRA_1000': 'CLORURO DE SODIO 0.9% 1000 MILILITROS PASAR VÍA INTRAVENOSA A 120 MILILITROS POR HORA',
  'SEDACION': 'SEDACIÓN:\n- PROPOFOL 1 GRAMO EN INFUSIÓN CONTINUA A DOSIS RESPUESTA VÍA INTRAVENOSA. AJUSTAR SEGÚN RESPUESTA CLÍNICA.',
  'ANALGESIA': 'ANALGESIA:\n- CLORURO DE SODIO 0.9% 100 MILILITROS MÁS 3 AMPOLLAS DE FENTANILO. PASAR VÍA INTRAVENOSA A DOSIS RESPUESTA.',
  'VASO': 'SOPORTE VASOPRESOR:\n- CLORURO DE SODIO 0.9% 100 MILILITROS MÁS 16 MILIGRAMOS DE NOREPINEFRINA. PASAR VÍA INTRAVENOSA A DOSIS RESPUESTA.',
  'BOMBA_DOLOR': 'BOMBA DE DOLOR (INFUSIÓN CONTINUA):\n- INICIAR FENTANILO EN BOMBA A 25-50 MCG/H (AJUSTAR SEGÚN DOLOR Y VIGILANCIA).\n- MONITORIZAR SIGNOS VITALES Y SEDACIÓN. AJUSTAR POR PESO Y RESPUESTA CLÍNICA.'
};
