const Map<String, String> examMacros = {
  'PIEL': 'PIEL Y FANERAS: SIN ALTERACIÓN, SIN SANGRADO EVIDENTE.',
  'CABEZA':
      'CABEZA: NORMOCEFALO, SIMETRICO, SIN MALFORMACIONES CRANEOFACIALES VISIBLES.',
  'OJOS': 'OJOS: VISION NORMAL, PUPILAS ISOCORICAS, REACTIVAS A LA LUZ.',
  'NARIZ': 'NARIZ: PERMEABLE, SIN SECRECIONES PATOLÓGICAS.',
  'BOCA': 'BOCA: MUCOSAS HÚMEDAS, NO LESIONES ORALES.',
  'OIDOS': 'OÍDOS: CONDUCTO AURICULAR SIN OBSTRUCCIÓN, AUDICIÓN PRESERVADA.',
  'OROFARINGE': 'OROFARINGE: AMIGDALAS SIN ENROJECIMIENTO EXCESIVO.',
  'CUELLO': 'CUELLO: SIN ADENOPATÍAS PALPABLES, SIN RIGIDEZ.',
  'TÓRAX': 'TÓRAX: SIMÉTRICO, MOVIMIENTOS RESPIRATORIOS CONSERVADOS.',
  'CAMPOS_PULMONARES':
      'CAMPOS PULMONARES: MURMULLO VESICULAR CONSERVADO, SIN ESTERTOS.',
  'RUIDOS_CARDIACOS': 'RUIDOS CARDIACOS: RITMO REGULAR, SIN SOPLOS CLAROS.',
  'ABDOMEN':
      'ABDOMEN: BLANDO, NO DISTENDIDO, DOLORES LOCALIZADOS SI LOS HUBIERA.',
  'EXTREMIDADES': 'EXTREMIDADES: SIN EDEMAS, PERFUSIÓN ADECUADA.',
  'NEURO': 'SISTEMA NEUROLÓGICO: MARCHA ESTABLE, REFLEJOS PRESENTES, ORIENTADO.'
};

const Map<String, String> labMacros = {
  'GASO': 'GASOMETRÍA ARTERIAL:\nPH: \nPCO2:  mmHg\nPO2:  mmHg\nHCO3:  mEq/L'
};

const Map<String, String> indiMacros = {
  'HIDRA_1000': 'CLORURO DE SODIO 0.9% 1000 ML PASAR IV 64 ML/HORA',
  'DOLOR': 'TERAPIA DEL DOLOR: KETOROLACO 60 MG PRN'
};
